#' Visualize decoded hidden states
#'
#' Generates two plots to visualize state assignments for (out-of-sample) state decoding:
#' one with solid colored points (fixed state assignment) and another where point
#' transparency (alpha) is weighted by the decoding probability. The data can be
#' \emph{out-of-sample}, meaning that they are new data on which the hidden Markov model was
#' not trained.
#'
#' @param list_results An object of class \code{epiquest_decoding} produced by \code{run_out_of_sample_decoding()}.
#' @param method A character string specifying the decoding method to visualize.
#' Must be one of \code{'filtering'} (default), \code{'local'}, or \code{'global'}.
#' @param print A logical. If \code{TRUE}, all generated plots are printed to the
#'   active graphics device.
#'
#' @details
#' Consult \code{\link{run_out_of_sample_decoding}} for information about the different
#' decoding options for method. The vertical dotted line marks the last index of the training
#' data for \code{hmm_frozen}. Data points to its right are the new out-of-sample data.
#'
#' The plots generated by \code{create_hmm_plots()} and \code{create_loop_plots()} all use \code{'local'}
#' state assignments.
#'
#' @return An object of class \code{epiquest_plot_list}, a named \code{list} of \code{ggplot2} objects containing:
#' \itemize{
#'   \item \code{time_series}: A ggplot object with points colored
#'     by the most likely state.
#'   \item \code{time_series_shaded}: A ggplot object similar to \code{time_series},
#'     but where point transparency represents state probability
#'     (not produced if \code{method = 'global'}).
#' }
#'
#' @seealso \code{\link{run_out_of_sample_decoding}}
#' @export
#' @importFrom rlang .data
create_decoding_plots <- function(
  list_results,
  method = "filtering",
  print = FALSE
) {
  # Perform input checks -------------------------------------------------------
  if (!inherits(list_results, "epiquest_decoding")) {
    stop("Input list_results must be an object of class 'epiquest_decoding' outputted by run_out_of_sample_decoding().")
  }

  if (length(method) != 1) {
    stop("You must choose a single method to decode the states.")
  }

  if (!method %in% c('global', 'local', 'filtering')) {
    stop("Input method needs to be either 'global', 'local' or 'filtering'.")
  }

  # Get state names ------------------------------------------------------------
  state_labels <- generate_state_labels_hmm(list_results$hmm_frozen$n_states)

  list_results$hmm_frozen$states <- list_results$hmm_frozen$states |>
    dplyr::arrange(.data$state) |>
    dplyr::mutate(state_label = factor(state_labels, levels = state_labels)) |>
    dplyr::mutate(state_label_rev = forcats::fct_rev(.data$state_label))

  method_selected <- method
  list_results$states <- list_results$states |>
    dplyr::filter(.data$method == method_selected) |>
    dplyr::left_join(list_results$hmm_frozen$states, by = "state")

  list_results$states <- list_results$states |>
    dplyr::left_join(
      list_results$probs |>
        dplyr::filter(.data$method == method_selected) |>
        dplyr::select("index", "state", "prob"),
      by = c("index", "state")
    )

  # Set plotting theme ---------------------------------------------------------
  scale_color_hmm <- generate_palette_hmm(n_states = list_results$hmm_frozen$n_states)
  scale_fill_hmm <- generate_palette_hmm(n_states = list_results$hmm_frozen$n_states, fill = TRUE)

  # Create plots ---------------------------------------------------------------
  plot_time_series <- list_results$states |>
    ggplot2::ggplot() +
    ggplot2::geom_vline(
      xintercept = max(list_results$hmm_frozen$data$index),
      linetype = "dotted",
      linewidth = 1
    ) +
    ggplot2::geom_line(
      ggplot2::aes(
        x = .data$index,
        y = .data$rate,
      ),
      color = "grey70",
      alpha = .5
    ) +
    ggplot2::geom_point(
      ggplot2::aes(
        x = .data$index,
        y = .data$rate,
        color = .data$state_label
      ),
      size = 2
    ) +
    scale_color_hmm +
    generate_ggplot_theme()

  if (list_results$hmm_frozen$type == "rate") {
    plot_time_series <- plot_time_series +
      ggplot2::scale_y_continuous(limits = \(x) range(c(x, 0))) +
      ggplot2::labs(
        x = "Week",
        y = "Rate",
        title = "Time series colored by decoded state"
      )
  } else if (list_results$hmm_frozen$type == "perc") {
    plot_time_series <- plot_time_series +
      ggplot2::scale_y_continuous(labels = scales::percent) +
      ggplot2::labs(
        x = "Week",
        y = "Percentage",
        title = "Time series colored by decoded state"
      )
  }

  plot_time_series_shaded <- list_results$states |>
    ggplot2::ggplot() +
    ggplot2::geom_vline(
      xintercept = max(list_results$hmm_frozen$data$index),
      linetype = "dotted",
      linewidth = 1
    ) +
    ggplot2::geom_line(
      ggplot2::aes(
        x = .data$index,
        y = .data$rate,
      ),
      color = "grey70",
      alpha = .5
    ) +
    ggplot2::geom_point(
      ggplot2::aes(
        x = .data$index,
        y = .data$rate,
        color = .data$state_label,
        alpha = .data$prob
      ),
      size = 2
    ) +
    scale_color_hmm +
    ggplot2::guides(alpha = "none") +
    generate_ggplot_theme()

  if (list_results$hmm_frozen$type == "rate") {
    plot_time_series_shaded <- plot_time_series_shaded +
      ggplot2::scale_y_continuous(limits = \(x) range(c(x, 0))) +
      ggplot2::labs(
        x = "Week",
        y = "Rate",
        title = "Time series colored by decoded state"
      )
  } else if (list_results$hmm_frozen$type == "perc") {
    plot_time_series_shaded <- plot_time_series_shaded +
      ggplot2::scale_y_continuous(labels = scales::percent) +
      ggplot2::labs(
        x = "Week",
        y = "Percentage",
        title = "Time series colored by decoded state (shaded by probability)"
      )
  }

  # Bundle output and return ---------------------------------------------------
  list_plots <- list(
    time_series_shaded = plot_time_series_shaded,
    time_series = plot_time_series
  )

  class(list_plots) <- c("epiquest_plot_list", "list")

  if (print) {
    print(list_plots)
    return(invisible(list_plots))
  }

  return(list_plots)
}
