#' Out-of-sample state decoding using a frozen HMM
#'
#' This function applies the parameters of a previously fitted hidden Markov model
#' (an \code{epiquest_hmm} object) to new data. It allows for
#' freezing of the HMM parameters (transition probabilities, emission
#' distributions and initial state distribution) and determining the hidden
#' states for new data without re-estimating the model.
#'
#' @param obs_data_new A \code{data.frame} containing the new observations.
#'   Must contain an \code{index} column and the same response columns
#'   (e.g., \code{rate} or \code{num}/\code{denom}) used to fit the \code{hmm_frozen}.
#'   If \code{seasonal = TRUE}, it must also contain a \code{season} column.
#' @param hmm_frozen An object of class \code{epiquest_hmm}. This is the
#'   fitted model object containing the parameters to be applied to the new data.
#' @param seasonal A logical. If \code{TRUE}, the function respects season
#'   boundaries in \code{obs_data_new} to prevent transitions between different
#'   seasons.
#'
#' @details
#' The function initializes a new \code{depmix} model using the structure of
#' \code{obs_data_new} and then uses \code{depmixS4::setpars} to hard-code the
#' parameters from \code{hmm_frozen}.
#'
#' This is particularly useful for prospective surveillance, where you want to
#' classify new weekly data using a model trained on historical seasons without
#' the new data points influencing the previously trained model.
#'
#' The states can be decoded according to different methods:
#'   \itemize{
#'     \item \code{'global'}: Uses the Viterbi algorithm to find the single
#'       \bold{most likely sequence} of states across the entire time series. This approach
#'       outputs a single state for each data point. There are no associated probabilities.
#'     \item \code{'local'}: Assigns the state with the \bold{highest posterior
#'       smoothing probability} at each specific time point.
#'     \item \code{'filtering'}: Similar to 'local', but performs real-time decoding,
#'       where the state at time \emph{t} is determined only by observations from
#'       time 1 to \emph{t}.
#'   }
#' Comparing 'local' and 'filtering', each approach has its advantages and disadvantages.
#' Filtering state assignments do not use information from the following week to determine states,
#' so they do not use all available information. When computed every week on new data as the data
#' arrive, the state assignments are stable. Local state assingments can change: they are only stable
#' once the data for the following week is available.
#'
#' The plots generated by \code{create_hmm_plots()} and \code{create_loop_plots()} all use \code{'local'}
#' state assignments.
#'
#' @return An object of class \code{epiquest_decode}. This is a list containing:
#' \itemize{
#'   \item \code{states}: The input \code{obs_data_new} with added columns for
#'     the predicted state and method used (see Details below).
#'   \item \code{probs}: For methods 'local' and 'filtering', the posterior probabilities
#'     for each of the states.
#' }
#' @export
#' @importFrom rlang .data
run_out_of_sample_decoding <- function(
  obs_data_new,
  hmm_frozen,
  seasonal = FALSE
) {
  # Perform input checks -------------------------------------------------------
  if (!inherits(hmm_frozen, "epiquest_hmm")) {
    stop("Input hmm_frozen must be an object of class 'epiquest_hmm' outputted by run_hmm().")
  }

  if (!is.data.frame(obs_data_new)) {
    stop("Input obs_data_new must be a data.frame.")
  }

  colnames_frozen <- colnames(hmm_frozen$data |> dplyr::select(-dplyr::starts_with("prob_"), -"state"))
  colnames_new <- colnames(obs_data_new)

  if (!all(colnames_frozen %in% colnames_new)) {
    stop("Input obs_data_new does not have correct columns.")
  }

  index_is_date <- inherits(obs_data_new$index, "Date") || inherits(obs_data_new$index, "POSIXt")
  index_is_int <- is.numeric(obs_data_new$index) && all(obs_data_new$index == as.integer(obs_data_new$index), na.rm = TRUE)
  if (!index_is_date && !index_is_int) {
    stop("Column obs_data_new$index must contain date or integer values.")
  }

  if (!is.logical(seasonal)) {
    stop("Input seasonal must be a logical (TRUE/FALSE).")
  }

  if (seasonal & (!"season" %in% colnames(obs_data_new))) {
    stop("Input obs_data must contain column 'season' if seasonal = TRUE.")
  }

  if (hmm_frozen$type == "rate") {
    if (!"rate" %in% colnames(obs_data_new)) {
      stop("Input obs_data_new must have column named rate.")
    }

    if (!is.numeric(obs_data_new$rate)) {
      stop("Column obs_data_new$rate column must be numeric.")
    }
  } else if (hmm_frozen$type == "perc") {
    if (!all(c("num", "denom") %in% colnames(obs_data_new))) {
      stop("Input obs_data_new must have columns named num and denom if input type is 'perc'.")
    }

    if (
      !all(
        is.numeric(obs_data_new$num) && all(obs_data_new$num == as.integer(obs_data_new$num)),
        is.numeric(obs_data_new$denom) && all(obs_data_new$denom == as.integer(obs_data_new$denom))
      )
    ) {
      stop("Columns num and denom in input obs_data_new must be integers.")
    }
  }

  indices_old <- hmm_frozen$data$index
  indices_new <- obs_data_new$index

  if (!all(max(indices_old) < indices_new)) {
    stop("Indices in input 'obs_data_new$index' must be after the maximum index in the training data for input 'hmm_frozen'.")
  }

  # Merge old and new data together --------------------------------------------
  if (seasonal) {
    obs_data_all <- dplyr::bind_rows(
      hmm_frozen$data |> dplyr::select("index", "rate", "season"),
      obs_data_new |> dplyr::select("index", "rate", "season")
    )
  } else {
    obs_data_all <- dplyr::bind_rows(
      hmm_frozen$data |> dplyr::select("index", "rate"),
      obs_data_new |> dplyr::select("index", "rate")
    )
  }

  # Make sure data are sorted chronologically
  obs_data_all <- obs_data_all |> dplyr::arrange(.data$index)

  # Extract season lengths -----------------------------------------------------

  # Get first week of new season
  if (seasonal) {
    list_index_end <- obs_data_all |>
      dplyr::mutate(row_number = dplyr::row_number()) |>
      dplyr::group_by(.data$season) |>
      dplyr::slice_tail(n = 1) |>
      dplyr::pull("row_number")

    list_season_length <- diff(c(0, list_index_end))
  } else {
    list_season_length <- NULL
  }

  # Get state conversion ------------------------------------------------------
  info_state_conversion <- tibble::tibble(
    state = paste0("L", 1:hmm_frozen$n_states),
    state_old = paste0("S", hmm_frozen$state_reorder)
  )

  # Define new HMM with new data -----------------------------------------------
  if (hmm_frozen$type == "rate") {
    hmm_new <- depmixS4::depmix(
      response = rate ~ 1,
      data = obs_data_all,
      nstates = hmm_frozen$n_states,
      ntimes = list_season_length,
      family = stats::gaussian()
    )
  } else if (hmm_frozen$type == "perc") {
    hmm_new <- depmixS4::depmix(
      response = cbind(num, denom - num) ~ 1,
      data = obs_data_all,
      nstates = hmm_frozen$n_states,
      ntimes = list_season_length,
      family = stats::binomial()
    )
  }

  # Transfer parameters from old/frozen model to new one -----------------------
  hmm_new <- depmixS4::setpars(hmm_new, depmixS4::getpars(hmm_frozen$model))

  # Compute states in different ways -------------------------------------------
  posterior_global <- depmixS4::posterior(hmm_new, type = "global")
  posterior_local <- depmixS4::posterior(hmm_new, type = "local")

  posterior_filtering <- depmixS4::posterior(hmm_new, type = "filtering")
  colnames(posterior_filtering) <- paste0("V", 1:ncol(posterior_filtering))

  posterior_smoothing <- depmixS4::posterior(hmm_new, type = "smoothing")
  colnames(posterior_smoothing) <- paste0("V", 1:ncol(posterior_smoothing))

  df_states_global <- obs_data_all |>
    dplyr::mutate(state_old = posterior_global) |>
    dplyr::mutate(state_old = paste0("S", .data$state_old)) |>
    dplyr::mutate(method = "global")

  df_states_local <- obs_data_all |>
    dplyr::mutate(state_old = posterior_local) |>
    dplyr::mutate(state_old = paste0("S", .data$state_old)) |>
    dplyr::mutate(method = "local")

  df_states_filtering <- posterior_filtering |>
    tibble::as_tibble(.name_repair = "unique") |>
    dplyr::rename_with(~ paste0("S", seq_along(.)), dplyr::everything())

  df_states_filtering <- df_states_filtering |>
    dplyr::mutate(state_old = names(df_states_filtering)[max.col(df_states_filtering, ties.method = "first")]) |>
    dplyr::mutate(method = "filtering")

  df_states_filtering <- dplyr::bind_cols(
    obs_data_all,
    df_states_filtering |> dplyr::select("state_old", "method")
  )

  # Gather results
  df_states <- dplyr::bind_rows(df_states_global, df_states_local, df_states_filtering) |>
    dplyr::arrange(.data$index, .data$method)

  # Convert new to old states
  df_states <- df_states |>
    dplyr::left_join(info_state_conversion, by = "state_old") |>
    dplyr::select(-"state_old") |>
    dplyr::relocate("state", .before = "method") |>
    dplyr::arrange(.data$method, .data$index, .data$state)

  # Compute probabilities in different ways ------------------------------------
  df_probs <- dplyr::bind_rows(
    posterior_smoothing |>
      tibble::as_tibble(.name_repair = "unique") |>
      dplyr::rename_with(~ paste0("S", seq_along(.)), dplyr::everything()) |>
      dplyr::bind_cols(obs_data_all) |>
      tidyr::pivot_longer(cols = dplyr::starts_with("S"), names_to = "state_old", values_to = "prob") |>
      dplyr::mutate(method = "local"),
    posterior_filtering |>
      tibble::as_tibble(.name_repair = "unique") |>
      dplyr::rename_with(~ paste0("S", seq_along(.)), dplyr::everything()) |>
      dplyr::bind_cols(obs_data_all) |>
      tidyr::pivot_longer(cols = dplyr::starts_with("S"), names_to = "state_old", values_to = "prob") |>
      dplyr::mutate(method = "filtering")
  )

  # Convert new to old states
  df_probs <- df_probs |>
    dplyr::left_join(info_state_conversion, by = "state_old") |>
    dplyr::select(-"state_old") |>
    dplyr::relocate("state", .before = "prob") |>
    dplyr::arrange(.data$method, .data$index, .data$state)

  # Bundle output and return ---------------------------------------------------
  list_results <- list(
    states = df_states,
    probs = df_probs,
    hmm_frozen = hmm_frozen
  )

  return(structure(list_results, class = c("epiquest_decoding", "list")))
}
